[package]
name = "elemental-chat-zome-chat"
version = "0.0.1"
authors = [ "michael.dougherty@holo.host" ]
edition = "2018"

[lib]
name = "chat"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "=1.0.104"
derive_more = "0.99.9"

# hdk3 = { path = "../../../chain/crates/hdk" }
hdk3 = { path = "../../../holochain-2020/crates/hdk" }