[package]
name = "elemental-chat"
version = "0.0.1-alpha19"
authors = [ "michael.dougherty@holo.host", "philip.beadle@holo.host", "david.meister@holo.host, tom.gowan@holo.host" ]
edition = "2018"

[lib]
name = "chat"
crate-type = [ "cdylib", "rlib" ]

[dependencies]

hdk3 = { git = "https://github.com/holochain/holochain.git", rev = "60da73e79397cbe21280edf9a3062ae325f0bf9a" }
serde = "=1.0.104"
chrono = { version = "0.4", features = ['alloc', 'std']}
derive_more = "0.99.9"
thiserror = "1.0.20"
