[package]
name = "elemental-chat"
version = "0.0.1-alpha7"
authors = [ "michael.dougherty@holo.host", "philip.beadle@holo.host", "david.meister@holo.host, tom.gowan@holo.host" ]
edition = "2018"

[lib]
name = "chat"
crate-type = [ "cdylib", "rlib" ]

[dependencies]

hdk3 = { git = "https://github.com/holochain/holochain.git", rev = "43b0f45bd2784f8b993085cbae714c8537c2e082" }
# hdk3 = { git = "https://github.com/holochain/holochain.git", rev = "bc2377395b08c06d54021978df3c365074fc2c10" }
serde = "=1.0.104"
chrono = { version = "0.4", features = ['alloc', 'std']}
derive_more = "0.99.9"
thiserror = "1.0.20"
