[workspace]
members = [
  "zomes/chat",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"


[patch.crates-io]
holochain_serialized_bytes = { version = "=0.0.40", git = "https://github.com/holochain/holochain-serialization.git", branch = "most-stringent-rmp-config" }
holochain_wasmer_guest = { version = "=0.0.37", git = "https://github.com/holochain/holochain-wasmer.git", branch = "extra-error-info" }
