[package]
name = "profile"
version = "0.1.0"
authors = ["zo-el <joel.ulahanna@holo.host>"]
edition = "2018"

[lib]
name = "profile"
crate-type = [ "cdylib", "rlib" ]
doctest = false

[dependencies]
profile = {git = "https://github.com/holochain/hc-zome-lib", branch = "develop", package = "profile"}
#hdk = "0"
hdk = {  git = "https://github.com/holochain/holochain.git", rev = "e157f64b67d5352cfba396b8088f90073879c8e0" }
hc_utils = "0"
