name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2
    - name: Use Nix
      uses: cachix/install-nix-action@v12
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure Nix substituters
      run: |
        set -xe
        mkdir -p ~/.config/nix/
        cp ./.github/nix.conf ~/.config/nix/
    - name: Prepare Nix environment
      run: nix-shell https://holochain.love --command "echo Completed"
    - name: Install correct version of holochain
      run: nix-shell  https://holochain.love  --command "cargo install --force holochain --git https://github.com/holochain/holochain.git --rev a82372a62d46a503e48f345360d0fb18cc5822d1"
#    - name: install correct version of hc
#      run: nix-shell  https://holochain.love  --command "cargo install --force --bin hc --git https://github.com/holochain/holochain.git --rev a82372a62d46a503e48f345360d0fb18cc5822d1"
    - name: Run all tests
      run: nix-shell https://holochain.love --run 'make test'
